Repository red-hat-storage/odf-cli, pull requests merged in 2025-04, with the labels that each got.

#137 Minor improvements in README.md
  README.md
Labels: lgtm, approved, needs-ok-to-test

#138 build(deps): update ramenctl to v0.3.4
  go.mod
  go.sum
Labels: lgtm, approved, ok-to-test

#132 Add resource collection for benchmark
  cmd/odf/benchmark/benchmark.go
  cmd/odf/benchmark/benchmark_resources.go
  cmd/odf/benchmark/benchmark_run.go
  cmd/odf/main.go
  cmd/odf/root/root.go
  pkg/benchmark/benchmark_run.go
  pkg/benchmark/resources.go
  pkg/benchmark/resources_test.go
Labels: lgtm, approved

#142 Syncing latest changes from main for odf-cli
  README.md
  cmd/odf/dr/dr.go
  cmd/odf/main.go
  docs/dr.md
  go.mod
  go.sum
Labels: lgtm, approved

#143 build(deps): updated ramenctl to v0.3.5
  go.mod
  go.sum
Labels: lgtm, approved, ok-to-test

#146 Syncing latest changes from main for odf-cli
  cmd/odf/benchmark/benchmark.go
  cmd/odf/benchmark/benchmark_resources.go
  cmd/odf/benchmark/benchmark_run.go
  cmd/odf/main.go
  cmd/odf/root/root.go
  go.mod
  go.sum
  pkg/benchmark/benchmark_run.go
  pkg/benchmark/resources.go
  pkg/benchmark/resources_test.go
Labels: lgtm, approved

#145 DFBUGS-1690: build: update go/jose version to v4.0.5
  go.mod
  go.sum
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#141 docs: add download-odf-nightly.sh script
  README.md
  scripts/download-odf-nightly.sh
Labels: lgtm, approved, ok-to-test

#148 DFBUGS-1732: build: update oauth to latest version
  go.mod
  go.sum
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference
