Repository red-hat-storage/odf-cli, pull requests merged in 2025-09, with the labels that each got.

#185 dr: add the `odf dr validate clusters` command
  README.md
  docs/dr.md
  go.mod
  go.sum
Labels: lgtm, approved, ok-to-test

#189 DFBUGS-3997: odf dr commands for 4.20
  README.md
  cmd/odf/dr/dr.go
  docs/dr.md
  go.mod
  go.sum
Labels: lgtm, approved, ok-to-test, jira/valid-bug, jira/valid-reference

#193 dr: update ramenctl to v0.11.1
  go.mod
  go.sum
Labels: lgtm, approved, ok-to-test

#202 subvolume: hide subvolume delete command for now
  cmd/odf/subvolume/subvolume.go
Labels: lgtm, approved
